name: betta
description: "A simple test."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 0.0.3+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: any
  qr_code_scanner: ^1.0.1
  sentry_flutter: ^8.6.0
  flutter_dotenv: ^5.0.2
  rive: ^0.13.9
  http: ^1.2.1
  cupertino_icons: ^1.0.6
  image_picker: any
  intl: any
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/validate.riv
    - assets/send.riv
    - assets/error.riv
    - assets/dots_loading.riv
    - .env

l10n:
  arb-dir: l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
